[build]
  command = "npm ci && npm run build"
  publish = "dist"

[[headers]]
  for = "/aksol-metadata.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/aksol_icon_512.png"
  [headers.values]
    Access-Control-Allow-Origin = "*"
